USE PROYECTO_ASADA;

/*Creación de las tablas de la base de datos*/

/*Tabla de medidas para los valores de las respuestas*/
CREATE TABLE MEDIDA( 
	ID INTEGER NOT NULL AUTO_INCREMENT, 
    Nombre VARCHAR (50),
    PRIMARY KEY ( ID )
  );
  
/*Tabla de provincias*/
CREATE TABLE PROVINCIA( 
  ID INTEGER NOT NULL, 
  Nombre VARCHAR (10),
  PRIMARY KEY ( ID )
  ) ;

/*Tabla de cantones*/
CREATE TABLE CANTON(
    ID           INTEGER NOT NULL ,
    Nombre       VARCHAR (20) ,
    Provincia_ID INTEGER NOT NULL,
    PRIMARY KEY ( ID, Provincia_ID )
  ) ;

/*Tabla de distritos*/
CREATE TABLE DISTRITO(
    ID                  INTEGER NOT NULL ,
    Nombre              VARCHAR (50) ,
    Canton_ID           INTEGER NOT NULL ,
    Provincia_ID INTEGER NOT NULL,
    Codigo 				INTEGER NOT NULL UNIQUE,
    PRIMARY KEY ( ID, Canton_ID, Provincia_ID ) 
  ) ;

/*Tabla de asadas*/
CREATE TABLE ASADA(
    ID                       INTEGER NOT NULL ,
    Nombre                       VARCHAR (150) ,
    Distrito_id                  INTEGER NOT NULL ,
    Latitud 					 VARCHAR (50),
    Longitud 					 VARCHAR (50),
    PRIMARY KEY ( ID )
  ) ;


/*Tabla de Componentes*/
CREATE TABLE COMPONENTE( 
	ID INTEGER NOT NULL AUTO_INCREMENT,
    Nombre VARCHAR (50) NOT NULL, 
    Valor REAL(6,3) NOT NULL,
    PRIMARY KEY ( ID )
  ) ;

/*Tabla de Subcomponentes*/
CREATE TABLE SUBCOMPONENTE( 
	ID INTEGER NOT NULL AUTO_INCREMENT, 
    Nombre VARCHAR (50), 
    Valor REAL(6,3) NOT NULL,
	Componente_ID INTEGER NOT NULL,
    CantPreguntas INTEGER,
    Siglas Varchar(5),
    PRIMARY KEY ( ID )
  ) ;

/*Tabla de Indicadores*/
CREATE TABLE INDICADOR(
    ID            INTEGER NOT NULL AUTO_INCREMENT,
    Codigo        VARCHAR (10) ,
    Subcomponente_ID INTEGER NOT NULL,
    Medida_ID     INTEGER NOT NULL,
    Nombre 	  VARCHAR(200) NOT NULL,
    Valor			 REAL(6,3) NOT NULL,
    PRIMARY KEY ( ID )
  ) ;

/*Tabla de Respuestas*/
CREATE TABLE INDICADORXASADA(
    ID               INTEGER NOT NULL AUTO_INCREMENT,
    Año              INTEGER NOT NULL ,
    Indicador_ID INTEGER NOT NULL ,
    Asada_ID     INTEGER NOT NULL,
    Valor			 REAL(6,3) NOT NULL,
    Texto			 VARCHAR(20) NOT NULL,
    PRIMARY KEY ( ID )
  );
  
  /*Tabla de Historico Respuestas*/
CREATE TABLE HISTORICORESPUESTA(
    ID               INTEGER NOT NULL,
    Año              INTEGER NOT NULL,
    Indicador_ID INTEGER NOT NULL,
    Asada_ID     INTEGER NOT NULL,
    Valor			 REAL(6,3) NOT NULL,
    Texto			 VARCHAR(20) NOT NULL,
    PRIMARY KEY ( ID )
  );

/*Tabla de Usuarios*/
CREATE TABLE USUARIO(
	ID INTEGER NOT NULL AUTO_INCREMENT, 
	Nombre varchar(100),
    Usuario varchar(50) NOT NULL UNIQUE,
    Contrasenna varchar(50),
    Tipo integer(1),    
    PRIMARY KEY ( ID )
);

/*Tabla de Lineal*/
CREATE TABLE LINEAL(
	ID INTEGER NOT NULL AUTO_INCREMENT,
    Pendiente REAL(6,3)  NULL,
    Ordenada REAL(6,3)  NULL,
    Indicador_ID INTEGER NULL,
    PRIMARY KEY ( ID )
);
/*Tabla de Nominales*/
CREATE TABLE NOMINAL(
	ID INTEGER NOT NULL AUTO_INCREMENT,
    Simbolo Varchar(2),
    Porcentaje REAL(6,3)  NULL,
    Valor 	INTEGER  NULL,
    Indicador_ID INTEGER NULL,
    PRIMARY KEY ( ID )
);

CREATE TABLE INDICADORINFO(
	ID INTEGER NOT NULL AUTO_INCREMENT,
    Indicador_ID INTEGER NULL,
    Descripcion Varchar(200),
    Formula Varchar(100),
    Fuente Varchar(100),
    Url Varchar(200),
    Responsable Varchar(100),
    Periodo Varchar(20),
    Observaciones Varchar(200),
    Frecuencia Varchar(20),
    PRIMARY KEY ( ID )
);

CREATE TABLE ASADAINFO(
	ID INTEGER NOT NULL AUTO_INCREMENT,
    Asada_ID INTEGER NULL,
    Ubicacion Varchar(200),
    Telefono Varchar(15),
    Poblacion Varchar(6),
    Url Varchar(200),
    cantAbonados Varchar(6),
    PRIMARY KEY ( ID )
);

CREATE TABLE USUARIOXASADA(
	ID INTEGER NOT NULL AUTO_INCREMENT,
    Usuario_ID INTEGER NULL,
    Asada_ID INTEGER NULL,
    PRIMARY KEY ( ID )
);




/*_______________REFERENCIAS FOREIGN KEYS_______________*/


/*REFERENCIA: ASADA-DISTRITO*/
ALTER TABLE Asada ADD CONSTRAINT ASADA_DISTRITO_FK FOREIGN KEY ( Distrito_ID ) REFERENCES DISTRITO ( Codigo ) ON DELETE CASCADE;

/*REFERENCIA: CANTON-PROVINCIA*/
ALTER TABLE CANTON ADD CONSTRAINT CANTON_PROVINCIA_FK FOREIGN KEY ( PROVINCIA_ID ) REFERENCES PROVINCIA ( ID ) ON DELETE CASCADE ;

/*REFERENCIA: DISTRITO-CANTON*/
ALTER TABLE DISTRITO ADD CONSTRAINT DISTRITO_CANTON_FK FOREIGN KEY ( CANTON_ID, PROVINCIA_ID ) REFERENCES CANTON ( ID, PROVINCIA_ID ) ON DELETE CASCADE ;

/*REFERENCIA: RESPUESTA-INDICADOR*/
ALTER TABLE IndicadorXAsada ADD CONSTRAINT INDICADOR_ASADA_IND_FK FOREIGN KEY ( Indicador_ID ) REFERENCES Indicador ( ID ) ON DELETE CASCADE ;

/*REFERENCIA: RESPUESTA-ASADA*/
ALTER TABLE IndicadorXAsada ADD CONSTRAINT INDICADOR_ASADA_ASD_FK FOREIGN KEY ( Asada_ID ) REFERENCES Asada ( ID ) ON  DELETE CASCADE;


/*REFERENCIA: INDICADOR-MEDIDA*/
ALTER TABLE Indicador ADD CONSTRAINT Indicador_Medida_FK FOREIGN KEY ( Medida_ID ) REFERENCES Medida ( ID ) ON DELETE CASCADE ;

/*REFERENCIA: INDICADOR-SUBCOMPONENTE*/
ALTER TABLE Indicador ADD CONSTRAINT Indicador_Subcomponente_FK FOREIGN KEY ( Subcomponente_ID ) REFERENCES Subcomponente ( ID ) ON DELETE CASCADE ;

/*REFERENCIA: SUBCOMPONENTE-COMPONENTE*/
ALTER TABLE Subcomponente ADD CONSTRAINT Subcomponente_Componente_FK FOREIGN KEY ( Componente_ID ) REFERENCES Componente ( ID ) ON DELETE CASCADE ;

/*REFERENCIA: NOMINAL-INDICADOR*/
ALTER TABLE Nominal ADD CONSTRAINT NOMINAL_INDICADOR_FK FOREIGN KEY ( Indicador_ID ) REFERENCES indicador ( ID ) ON DELETE CASCADE ;

/*REFERENCIA: LINEAL-INDICADOR*/
ALTER TABLE Lineal ADD CONSTRAINT LINEAL_INDICADOR_FK FOREIGN KEY ( Indicador_ID ) REFERENCES indicador ( ID ) ON DELETE CASCADE ;

/*REFERENCIA: INDICADORINFO-INDICADOR*/
ALTER TABLE IndicadorInfo ADD CONSTRAINT INFO_INDICADOR_FK FOREIGN KEY ( Indicador_ID ) REFERENCES indicador ( ID ) ON DELETE CASCADE ;

/*REFERENCIA: ASADAINFO-ASADA*/
ALTER TABLE AsadaInfo ADD CONSTRAINT INFO_ASADA_FK FOREIGN KEY ( Asada_ID ) REFERENCES Asada ( ID ) ON DELETE CASCADE ;

/*REFERENCIA: USUARIOASADA-ASADA*/
ALTER TABLE UsuarioXAsada ADD CONSTRAINT USUARIOASADA_ASADA_FK FOREIGN KEY ( Asada_ID ) REFERENCES Asada ( ID ) ON DELETE CASCADE ;

/*REFERENCIA: USUARIOASADA-USUARIO*/
ALTER TABLE UsuarioXAsada ADD CONSTRAINT USUARIOASADA_USUARIO_FK FOREIGN KEY ( Usuario_ID ) REFERENCES Usuario ( ID ) ON DELETE CASCADE ;
