LOAD DATA LOCAL INFILE 'Nuevar-asadas-cartago.csv' INTO TABLE ASADA
  FIELDS TERMINATED BY ','
  OPTIONALLY ENCLOSED BY '"'
  LINES TERMINATED BY '\n' IGNORE 1 rows;

LOAD DATA LOCAL INFILE 'ASADASINFO-CARTAGO.csv' INTO TABLE ASADAINFO
  FIELDS TERMINATED BY ','
  OPTIONALLY ENCLOSED BY '"'
  LINES TERMINATED BY '\n' IGNORE 1 rows (Asada_ID, Ubicacion, Telefono, Url, Poblacion,cantAbonados);

LOAD DATA LOCAL INFILE 'INDICADORXASADA-CARTAGO.csv' INTO TABLE INDICADORXASADA
  FIELDS TERMINATED BY ','
  OPTIONALLY ENCLOSED BY '"'
  LINES TERMINATED BY '\n' IGNORE 1 rows (Año,Indicador_id,Asada_id,Valor,Texto);
